'use strict';
const slides=window.reviewSlides;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const validMode=['visual','text','notes'];
let current=1,selected=0,mode='visual',visible=[];
function counts(s){return {slide:s.changes.filter(c=>c.type==='slide').length,notes:s.changes.filter(c=>c.type==='notes').length};}
function preferredMode(s){const c=counts(s);return c.notes&&!c.slide?'notes':'visual';}
function locationLabel(s){const c=counts(s);return c.slide&&c.notes?'Slide + notes':c.notes?'Notes only':c.slide?'On-slide fixes':'Unchanged';}
function pill(label,value){return `<span class="pill ${value.toLowerCase().replace(' ','-')}">${esc(label)} <b>${esc(value)}</b></span>`;}
function diff(a,b){const x=a.split(/\s+/).filter(Boolean),y=b.split(/\s+/).filter(Boolean),d=Array.from({length:x.length+1},()=>new Uint16Array(y.length+1));for(let i=x.length-1;i>=0;i--)for(let j=y.length-1;j>=0;j--)d[i][j]=x[i]===y[j]?1+d[i+1][j+1]:Math.max(d[i+1][j],d[i][j+1]);const left=[],right=[];let i=0,j=0;while(i<x.length||j<y.length){if(i<x.length&&j<y.length&&x[i]===y[j]){left.push(esc(x[i++]));right.push(esc(y[j++]));}else if(i<x.length&&(j===y.length||d[i+1][j]>=d[i][j+1]))left.push('<del>'+esc(x[i++])+'</del>');else right.push('<ins>'+esc(y[j++])+'</ins>');}return [left.join(' '),right.join(' ')];}
function readHash(){const p=new URLSearchParams(location.hash.slice(1));const n=Number(p.get('slide'));if(n>=1&&n<=67)current=n;if(validMode.includes(p.get('view')))mode=p.get('view');if(['original','priority','confidence'].includes(p.get('sort')))$('sort').value=p.get('sort');if(['all','changed','high','unchanged','hidden'].includes(p.get('filter')))$('filter').value=p.get('filter');$('search').value=p.get('q')||'';if(preferredMode(slides[current-1])==='notes')mode='notes';}
function saveHash(){const p=new URLSearchParams({slide:current,view:mode,sort:$('sort').value,filter:$('filter').value});if($('search').value.trim())p.set('q',$('search').value.trim());history.replaceState(null,'','#'+p.toString());}
function getVisible(){const query=$('search').value.toLocaleLowerCase().trim(),filter=$('filter').value;const result=slides.filter(s=>{const match=!query||String(s.slide)===query||[s.title,s.originalTitle,s.summary,s.remaining,...s.changes.map(c=>c.why)].join(' ').toLocaleLowerCase().includes(query);return match&&(filter==='all'||filter==='changed'&&s.changes.length||filter==='pending'&&s.remaining||filter==='high'&&s.priority===3||filter==='unchanged'&&!s.changes.length||filter==='hidden'&&s.hidden);});const sort=$('sort').value;result.sort((a,b)=>sort==='priority'?b.priority-a.priority||b.confidence-a.confidence||a.slide-b.slide:sort==='confidence'?b.confidence-a.confidence||b.priority-a.priority||a.slide-b.slide:a.slide-b.slide);return result;}
function renderRail(){const scroll=$('slides').scrollTop;visible=getVisible();if(visible.length&&!visible.some(s=>s.slide===current)){current=visible[0].slide;selected=0;mode=preferredMode(slides[current-1]);}const sortLabel=$('sort').selectedOptions[0].textContent;$('result-count').textContent=`${visible.length} OF 67 SLIDES`;$('slides').innerHTML=visible.map((s,index)=>`<button class="slide-nav" aria-current="${s.slide===current}" data-slide="${s.slide}" aria-label="${sortLabel==='Original order'?'Slide':'Rank '+(index+1)+', slide'} ${s.slide}: ${esc(s.title)}. Priority ${s.priorityLabel}, confidence ${s.confidenceLabel}."><img loading="lazy" src="assets/thumb-${s.slide}.webp" alt=""><span class="nav-copy"><span class="nav-caption"><span class="slide-number">${String(s.slide).padStart(2,'0')}</span>${esc(s.title)}</span><span class="nav-type"><span class="priority-dot level-${s.priority}"></span>${s.priorityLabel==='No change'?'No changes':$('sort').value==='confidence'?s.confidenceLabel+' confidence':s.priorityLabel+' priority'}${s.hidden?' · Hidden':''}</span><span class="nav-location">${locationLabel(s)}</span></span></button>`).join('');$('slides').scrollTop=scroll;$('announcement').textContent=`${visible.length} slides. ${sortLabel}.`;}
function renderSlide(){const s=slides[current-1];$('empty').hidden=visible.length>0;$('review-content').hidden=!visible.length;if(!visible.length){saveHash();return;}if(selected>=s.changes.length)selected=0;
const position=visible.findIndex(x=>x.slide===current);$('prev').disabled=position===0;$('next').disabled=position===visible.length-1;$('position').textContent=`${position+1} / ${visible.length}`;
$('indicator').textContent=`Original slide ${s.slide} · Revised slide ${s.revisedPosition}${s.indicator==='Section'?' · Section introduction':''}`;$('title').textContent=s.title;$('summary').textContent=s.changes.length?`${s.changes.length} proposed suggestion${s.changes.length===1?'':'s'}${s.remaining?' · Evidence or verification still needed':''}`:'Reviewed — no specific correction proposed.';
$('priority-rating').innerHTML=pill('Priority',s.priorityLabel);$('confidence-rating').innerHTML=pill('Confidence',s.confidenceLabel);$('priority-reason').textContent=`Priority — ${s.priorityReason}`;$('confidence-reason').textContent=`Confidence — ${s.confidenceReason}`;$('hidden-badge').hidden=!s.hidden;
const types=counts(s);
$('summary').textContent=s.changes.length?[types.slide?`${types.slide} on-slide fix${types.slide===1?'':'es'}`:'',types.notes?`${types.notes} presenter-note fix${types.notes===1?'':'es'}`:''].filter(Boolean).join(' / '):'Reviewed - no specific correction proposed.';
validMode.forEach(v=>$(v).setAttribute('aria-pressed',mode===v));$('highlight-label').hidden=mode!=='visual'||!types.slide;
const viewChanged=mode==='notes'?types.notes>0:types.slide>0;
$('change-location').hidden=!s.changes.length;
$('change-location').innerHTML=types.notes&&!types.slide?`<div><strong>Presenter notes only. The slide itself is unchanged.</strong><p>${mode==='notes'?'Compare the removed wording on the left with the replacement on the right.':'Both slide images are intentionally identical. Open the notes to see the correction.'}</p></div>${mode!=='notes'?'<button id="compare-notes" class="outline">Compare notes</button>':''}`:!viewChanged?'<div><strong>Presenter notes are unchanged.</strong><p>Open Slide view or Text changes to see the on-slide fixes.</p></div>':`<div><strong>${mode==='notes'?'Presenter-note changes':'On-slide changes'}</strong><p>${mode==='visual'?'Numbered highlights show the locations of the fixes. Open Text changes for the exact wording.':'Removed wording is marked on the left; replacement wording is highlighted on the right.'}${types.slide&&types.notes?' This slide also has '+(mode==='notes'?'on-slide fixes.':'presenter-note fixes.') : ''}</p></div>`;

const noteDiff=mode==='notes'?diff(s.originalNotes,s.revisedNotes):null;
const textChanges=s.changes.map((c,i)=>({...c,index:i})).filter(c=>c.type==='slide');
const textDiff=mode==='text'?textChanges.map(c=>diff(c.before,c.after)):[];
$('comparison').innerHTML=['original','revised'].map((version,v)=>{const title=mode==='notes'?(v?'Revised presenter notes':'Original presenter notes'):(v?(viewChanged?'Suggested revision':'Slide unchanged'):'Original');let body;
if(mode==='visual')body=`<div class="slide-image"><img src="assets/${version}-${s.slide}.png?v=selected-1" alt="${title} slide: ${esc(s.title)}"><div class="hotspots">${$('highlight').checked?textChanges.map(c=>{const r=c.rect;return `<button class="hotspot ${selected===c.index?'active':''}" data-change="${c.index}" aria-label="Suggestion ${c.index+1}: ${esc(c.label)}" style="left:${Math.max(0,r[0])}%;top:${Math.max(0,r[1])}%;width:${Math.min(r[2],100-r[0])}%;height:${Math.min(r[3],100-r[1])}%"><span>${c.index+1}</span></button>`;}).join(''):''}</div></div><div class="card-foot"><span>Slide ${v?s.revisedPosition:s.slide} · PowerPoint export</span><button class="enlarge" data-zoom="${version}">Enlarge ↗</button></div>`;
else if(mode==='notes')body=`<div class="text-block notes-text">${s.originalNotes===s.revisedNotes?`<p class="plain-text">${esc((v?s.revisedNotes:s.originalNotes)||'No presenter notes.')}</p>`:`<p>${noteDiff[v]||'<em>No presenter notes in this version.</em>'}</p>`}</div>`;
else body='<div class="text-block">'+(textChanges.length?textChanges.map((c,i)=>`<div data-active="${c.index===selected}"><h3>Suggestion ${c.index+1} · ${esc(c.label)}</h3><p>${textDiff[i][v]||'<em>Removed from this version.</em>'}</p></div>`).join(''):`<p class="muted">Visible text is unchanged${s.changes.some(c=>c.type==='notes')?'; see Presenter notes for changes':''}.</p><p class="plain-text">${esc((v?s.revisedText:s.originalText)||'This slide contains visual content only.')}</p>`)+'</div>';
return `<article class="slide-card ${version}"><div class="card-head"><span>${title}</span><span class="version">${v?(viewChanged?'PROPOSED':'UNCHANGED'):'AS RECEIVED'}</span></div>${body}</article>`;}).join('');
$('pending-panel').hidden=!s.remaining;$('remaining').textContent=s.remaining;$('change-count').textContent=`${s.changes.length} suggestion${s.changes.length===1?'':'s'}`;
$('changes').innerHTML=s.changes.length?s.changes.map((c,i)=>`<article class="change ${i===selected?'selected':''}"><button class="change-toggle" data-change="${i}" aria-expanded="${i===selected}" aria-controls="detail-${i}"><span class="num">${i+1}</span><span>${esc(c.label)}<small>${c.type==='notes'?'Presenter notes':c.type==='structure'?'Deck organization':'On-slide content'}</small></span><span class="chevron">${i===selected?'−':'+'}</span></button><div id="detail-${i}" class="change-detail" ${i!==selected?'hidden':''}><p>${esc(c.why)}</p><div class="suggestion-ratings">${pill('Priority',c.severity)}${pill('Confidence',c.confidence)}</div><p class="rating-explanation"><strong>Priority:</strong> ${esc(c.severityReason)} <strong>Confidence:</strong> ${esc(c.confidenceReason)}</p><div class="evidence"><strong>BASIS FOR THIS SUGGESTION</strong>${esc(c.evidence||s.source||'Supplied deck, rendered slide, and editorial review.')}${c.evidenceAsset?'<br>Screenshot source: '+esc(c.evidenceAsset):''}</div>${c.type==='structure'?`<p class="move-detail">${esc(c.before)} → ${esc(c.after)}</p>`:''}</div></article>`).join(''):'<div class="unchanged"><strong>Keep as received.</strong><p>No clear-cut fix is included for this slide. The original content is preserved.</p></div>';
document.querySelector('.sources-panel').hidden=!s.changes.length;$('finding').textContent=s.finding;$('source').textContent=s.source?'Evidence reviewed: '+s.source:'Basis: supplied slide and visual review.';
$('links').innerHTML=s.links.length?s.links.map(l=>`<div class="source-link"><span class="link-status ${l.status==='Viewer reachable'?'reachable':'restricted'}">${esc(l.status)}</span><a href="${esc(l.url)}" target="_blank" rel="noopener noreferrer">${esc(new URL(l.url).hostname)} · Open original evidence ↗</a><span class="link-retained">${l.retained?'Retained in revised slide':'Not retained as a revised-slide link'}</span></div>`).join(''):'<p class="muted">No externally checked evidence link on this slide.</p>';saveHash();}
function render(){renderRail();renderSlide();}
function go(n){current=n;selected=0;mode=preferredMode(slides[n-1]);render();$('announcement').textContent=`Original slide ${n}: ${slides[n-1].title}`;}
function reset(){$('search').value='';$('filter').value='all';$('sort').value='original';render();}
document.addEventListener('click',e=>{if(e.target.closest('#compare-notes')){mode='notes';renderSlide();$('notes').focus();}const n=e.target.closest('[data-slide]');if(n){go(+n.dataset.slide);document.querySelector(`[data-slide="${current}"]`)?.focus({preventScroll:true});}const c=e.target.closest('[data-change]');if(c){selected=+c.dataset.change;const change=slides[current-1].changes[selected];if(change.type==='notes')mode='notes';else if(change.type==='slide'&&mode==='notes')mode='visual';renderSlide();document.querySelector(`#changes [data-change="${selected}"]`)?.focus({preventScroll:true});}const z=e.target.closest('[data-zoom]');if(z){const s=slides[current-1];$('zoom-title').textContent=`${z.dataset.zoom==='original'?'Original slide '+s.slide:'Revised slide '+s.revisedPosition} · ${s.title}`;$('zoom-image').src=`assets/${z.dataset.zoom}-${s.slide}.png?v=selected-1`;$('zoom-image').alt=$('zoom-title').textContent;$('zoom').showModal();}});
$('prev').onclick=()=>{const i=visible.findIndex(s=>s.slide===current);if(i>0)go(visible[i-1].slide);};$('next').onclick=()=>{const i=visible.findIndex(s=>s.slide===current);if(i<visible.length-1)go(visible[i+1].slide);};
validMode.forEach(v=>$(v).onclick=()=>{mode=v;renderSlide();});$('highlight').onchange=renderSlide;$('sort').onchange=render;$('filter').onchange=render;$('search').oninput=render;$('reset').onclick=reset;$('empty-reset').onclick=reset;
$('close').onclick=()=>$('zoom').close();$('downloads').onclick=()=>$('download-dialog').showModal();$('close-downloads').onclick=()=>$('download-dialog').close();
document.addEventListener('keydown',e=>{if($('zoom').open||$('download-dialog').open||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.key==='ArrowRight'){$('next').click();e.preventDefault();}if(e.key==='ArrowLeft'){$('prev').click();e.preventDefault();}});
window.addEventListener('hashchange',()=>{readHash();render();});
$('edited-count').textContent=slides.filter(s=>s.changes.length).length;$('suggestion-count').textContent=slides.reduce((sum,s)=>sum+s.changes.length,0);$('pending-count').textContent=slides.filter(s=>!s.changes.length).length;
readHash();render();
